### ISSUE TITLE
Сервисы закрылись

### ISSUE THREAD

**Issue by koutoftimer** [bacher09/ua-vlc-scripts#3]
Оба сервиса уже давно закрыты... Можно смело архивировать репу.

**Comment by bacher09** [comment]
Во первых тут поддерживается [3 сервиса](https://github.com/bacher09/ua-vlc-scripts/tree/beta/playlist). Во вторых, несмотря на то что которые есть сейчас не работают, появились другие и их можно будет добавить сюда.

Плюс, в конечном итоге репу потом может удалю (если не добавлю новых сервисов). Так-что архивировать не имеет смысла.

**Comment by bacher09** [comment]
Хотя добавить инфу что репа outdated всё-таки можно.

**Comment by koutoftimer** [comment]
@bacher09 по поводу 3его:

```
$ host http://movietrailer.com.ua
Host http://movietrailer.com.ua not found: 3(NXDOMAIN)
```

Да, ты прав по поводу "outdated". Погорячился я с архивированием, как минимум, эта репа -  хороший пример как делать parser-ы для других сервисов.
